export const whatsapp = (text: string) => `https://wa.me/917306982905?text=${encodeURIComponent(text)}`;
export const enquiry = (subject?: string) => whatsapp(subject ? `Hello Hommet, I would like to enquire about ${subject}.` : "Hello Hommet, I would like to discuss my project.");
export const quotation = (subject: string) => whatsapp(`Hello Hommet, I would like to request a quotation for ${subject}. Please help me with the available options and pricing.`);
export const categories = [
  {id:"roofing",interiorAlt:"Attic room with skylights set into a sloping timber ceiling",name:"Roofing & Building Materials",label:"From the ground up",image:"roofing-hero.jpg",alt:"House with a standing-seam roof",focus:"center 59%",credit:{label:"Roofit.Solar",href:"https://roofit.solar/"},description:"Explore roofing and building materials with Hommet. Ask our team about Atlantique roofing and the options for your project."},
  {id:"doors",interiorAlt:"Bright living room with a tall window and sofa",name:"Doors & Windows",label:"A welcome to your world",image:"doors.jpg",alt:"A window bringing natural light into a home",description:"Explore doors and windows, including STALY steel doors and Leoplast UPVC. Speak to us about your space and requirements."},
  {id:"sealants",interiorAlt:"Modern kitchen with a tiled backsplash and bar stools",name:"Sealants & Construction Accessories",label:"The details that bring it together",image:"sealants.jpg",alt:"Caulking gun for construction sealants",contain:true,description:"Talk to our team about sealants and construction accessories for your application. Request availability and product information."},
  {id:"terracotta",interiorAlt:"Living room with an exposed brick wall",name:"Architectural Terracotta",label:"Texture with character",image:"terracotta.jpg",alt:"Patterned architectural terracotta wall tiles",description:"Discover architectural terracotta with Hommet. Share your design requirements to learn about the available range."},
  {id:"sanitary",interiorAlt:"Bathroom with a long vanity and washbasins",name:"Sanitary Ware",label:"Considered everyday spaces",image:"sanitary.jpg",alt:"White ceramic bathroom washbasin",description:"Explore sanitary ware for your bathroom. Get in touch for product options and details."},
  {id:"toilets",interiorAlt:"White bathroom with a toilet and timber floor",name:"Smart Toilets",label:"Thoughtfully modern living",image:"toilets.jpg",alt:"An automatic toilet with integrated controls",focus:"center 30%",description:"Ask about smart toilet options for your home, including confirmed features and installation requirements."},
  {id:"fitness",interiorAlt:"Person exercising with dumbbells in a home workout space",name:"Home Fitness Equipment",label:"Make room for movement",image:"fitness.jpg",alt:"Cardio equipment in a light-filled gym",description:"Find out about home fitness equipment. Share your available space and requirements with the Hommet team."},
  {id:"hvac",interiorAlt:"Room with a wall-mounted air conditioner above the window",name:"HVAC Solutions",label:"Comfort, carefully considered",image:"hvac.jpg",alt:"Outdoor air-conditioning equipment",description:"Discuss your HVAC requirements with Hommet. For Armstrong enquiries, contact Nirmal Kiran at nirmal.kiran@hommet.in or +91 90721 21337."},
  {id:"pumps",interiorAlt:"Pressure gauge on pipework in a plant room",name:"Pumps & Fluid Systems",label:"The systems behind your space",image:"pumps.jpg",alt:"A centrifugal water pump",contain:true,description:"Speak to us about pumps and fluid systems for your application. Armstrong-specific technical enquiries go to nirmal.kiran@hommet.in."},
  {id:"automation",interiorAlt:"Living room with a smart-home screen on the wall",name:"Building Automation / Performance Solutions",label:"Connected to the way you live",image:"automation.jpg",alt:"A wall-mounted digital thermostat",description:"Discuss building automation and performance requirements with our team. Request confirmed scope and technical information for your project."},
];
export const offices = [
 {city:"Pathanamthitta",address:"258, Sivasylam, Kadampanad, Adoor, Pathanamthitta, Kerala 691552"},
 {city:"Ernakulam",address:"Aimury Kavala, Koovapady Post, Perumbavoor, Ernakulam 683544"},
 {city:"Bengaluru",address:"3rd Floor, Flat No. 50, 9th A Main Road, Binnamangala, Indiranagar, Bengaluru, Karnataka 560038"},
];
